---
title: "Cleaning - Intermediate R Course"
author: "Kasper Mortensen"
format: html
---

## Header 1

```{r setup}
#| include: false
source(here::here("R/functions.R"))
```

## Prepare HR data

```{r}
list_summarise_on <- list(mean = mean, median = median, sd = sd)

hr_data <- read_sensor_data(filename = "HR.csv.gz", fns = list_summarise_on, unit = "minutes")
ibi_data <- read_sensor_data(filename = "IBI.csv.gz", fns = list_summarise_on, unit = "minutes")
temp_data <- read_sensor_data(filename = "TEMP.csv.gz", fns = list_summarise_on, unit = "minutes")
bvp_data <- read_sensor_data(filename = "BVP.csv.gz", fns = list_summarise_on, unit = "minutes")
eda_data <- read_sensor_data(filename = "EDA.csv.gz", fns = list_summarise_on, unit = "minutes")
```

## Process survey data
```{r}
survey_tidy <- here::here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read() |>
  tidy_survey_dates()

survey_long <- survey_tidy |>
  survey_to_long()
```

## Joining datasets
```{r}
nurses_stress <- survey_long |>
  dplyr::full_join(survey_tidy) |>
  dplyr::full_join(hr_data) |>
  dplyr::full_join(ibi_data) |>
  dplyr::full_join(temp_data) |>
  dplyr::full_join(bvp_data) |>
  dplyr::full_join(eda_data)

readr::write_csv(nurses_stress, here::here("data/nurses-stress.csv"))
```
