---
title: "Draft Quarto document"
author: "Kasper Mortensen"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(here)
library(snakecase)

source(here("R/functions.R"))

# {r setup} tells R to run this chunk first
```

## Importing new data

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case, # does the same as clean_names, needs to library(snakecase)
    n_max = 100
  )


## NOTES ##
# snakecase -> all lower letters separated by _ (best practice)
# camelCase
# PascalCase
```

## Exercise: Reading other files.
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case # does the same as clean_names from janitor
  )

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )

here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )

here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Making a function to add numbers

```{r}
# Roxygen skeleton (choose from palette with cursor inside the function)
# -> @export and @examples is for packages so they are deleted below
# A way of describing what the function does

#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of the two numbers.
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

add_numbers(1, 2)
```

## Import 5C's HR data with a function
```{r}
#| eval: false
# When making names, check in console ?name if the name exists

#' Read in one nurses' stress data file.
#'
#' @param file_path Path to the data file.
#'
#' @returns Outputs a data frame/tibble.
#'
read <- function(file_path) {
  data <- file_path |>
    readr::read_csv( # readr:: added at the end of day 1
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = 100
    )
  return(data)
}

# don't load packages inside functions
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```

## Add max rows to the function
```{r}
#| eval: false
# When making names, check in console ?name if the name exists

#' Read in one nurses' stress data file.
#'
#' @param file_path Path to the data file.
#' @param max_rows max number of rows loaded
#'
#' @returns Outputs a data frame/tibble.
#'
read <- function(file_path, max_rows = 100) {
  data <- file_path |>
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = max_rows
    )
  return(data)
}

# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```


```{r}
## Play around a bit
#| eval: false

# When making names, check in console ?name if the name exists

#' Read in one nurses' stress data file.
#'
#' @param file_path Path to the data file.
#' @param max_rows max number of rows loaded
#'
#' @returns Outputs a data frame/tibble.
#'
read <- function(file_path, max_rows = 100) {
  data <- read_csv(file_path,
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = max_rows
  )
  return(data)
}
# above works as well, and does the same according to the instructor. The other way
# with piping might be better, especially when you copy and paste function
```
